services:
  db:
    image: postgres:17
    container_name: syrinx_db
    environment:
      # If you change these variables remember to update your .env file
      POSTGRES_DB: syrinx
      POSTGRES_USER: syrinx
      POSTGRES_PASSWORD: syrinx
    ports:
      - "5432:5432"
    volumes:
      - syrinx_postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syrinx"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  syrinx_postgres_data:

networks:
  app_network:
    driver: bridge
