// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A user's cryptographic signature over content, and the id of the key
// that produced it.
type UserSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Armor         string                 `protobuf:"bytes,2,opt,name=armor,proto3" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignature) Reset() {
	*x = UserSignature{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignature) ProtoMessage() {}

func (x *UserSignature) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignature.ProtoReflect.Descriptor instead.
func (*UserSignature) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserSignature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSignature) GetArmor() string {
	if x != nil {
		return x.Armor
	}
	return ""
}

// The home server's countersignature, and when it was produced.
type ServerSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Armor         string                 `protobuf:"bytes,2,opt,name=armor,proto3" json:"armor,omitempty"`
	SignedAt      int64                  `protobuf:"varint,3,opt,name=signed_at,json=timestamp,proto3" json:"signed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSignature) Reset() {
	*x = ServerSignature{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSignature) ProtoMessage() {}

func (x *ServerSignature) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSignature.ProtoReflect.Descriptor instead.
func (*ServerSignature) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ServerSignature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerSignature) GetArmor() string {
	if x != nil {
		return x.Armor
	}
	return ""
}

func (x *ServerSignature) GetSignedAt() int64 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

// Every non-2xx HTTP body. detail carries the certificate a refusal or a
// 410 is backed by, when there is one.
type Error struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Detail:
	//
	//	*Error_AccountRemoval
	//	*Error_ReedRemoval
	//	*Error_ThreadRemoval
	//	*Error_Block
	Detail        isError_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetail() isError_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Error) GetAccountRemoval() *AccountRemovalCert {
	if x != nil {
		if x, ok := x.Detail.(*Error_AccountRemoval); ok {
			return x.AccountRemoval
		}
	}
	return nil
}

func (x *Error) GetReedRemoval() *ReedRemovalCert {
	if x != nil {
		if x, ok := x.Detail.(*Error_ReedRemoval); ok {
			return x.ReedRemoval
		}
	}
	return nil
}

func (x *Error) GetThreadRemoval() *ThreadRemoval {
	if x != nil {
		if x, ok := x.Detail.(*Error_ThreadRemoval); ok {
			return x.ThreadRemoval
		}
	}
	return nil
}

func (x *Error) GetBlock() *BlockCert {
	if x != nil {
		if x, ok := x.Detail.(*Error_Block); ok {
			return x.Block
		}
	}
	return nil
}

type isError_Detail interface {
	isError_Detail()
}

type Error_AccountRemoval struct {
	AccountRemoval *AccountRemovalCert `protobuf:"bytes,2,opt,name=account_removal,json=accountRemoval,proto3,oneof"`
}

type Error_ReedRemoval struct {
	ReedRemoval *ReedRemovalCert `protobuf:"bytes,3,opt,name=reed_removal,json=reedRemoval,proto3,oneof"`
}

type Error_ThreadRemoval struct {
	ThreadRemoval *ThreadRemoval `protobuf:"bytes,4,opt,name=thread_removal,json=threadRemoval,proto3,oneof"`
}

type Error_Block struct {
	Block *BlockCert `protobuf:"bytes,5,opt,name=block,proto3,oneof"`
}

func (*Error_AccountRemoval) isError_Detail() {}

func (*Error_ReedRemoval) isError_Detail() {}

func (*Error_ThreadRemoval) isError_Detail() {}

func (*Error_Block) isError_Detail() {}

type Ripple struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hash     string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ThreadId string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadID,proto3" json:"thread_id,omitempty"`
	UserId   string                 `protobuf:"bytes,3,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Content  string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Unset when this ripple is not a reply to another ripple.
	ReplyingTo      *string          `protobuf:"bytes,5,opt,name=replying_to,json=replyingTo,proto3,oneof" json:"replying_to,omitempty"`
	Deleted         bool             `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	PostedAt        int64            `protobuf:"varint,7,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	UserSignature   *UserSignature   `protobuf:"bytes,8,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature `protobuf:"bytes,9,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ripple) Reset() {
	*x = Ripple{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ripple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ripple) ProtoMessage() {}

func (x *Ripple) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ripple.ProtoReflect.Descriptor instead.
func (*Ripple) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Ripple) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Ripple) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Ripple) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ripple) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Ripple) GetReplyingTo() string {
	if x != nil && x.ReplyingTo != nil {
		return *x.ReplyingTo
	}
	return ""
}

func (x *Ripple) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Ripple) GetPostedAt() int64 {
	if x != nil {
		return x.PostedAt
	}
	return 0
}

func (x *Ripple) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *Ripple) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// Cryptographic certificate proving a reed's removal, signed by both
// the removing user and their home server.
type ReedRemovalCert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverID,proto3" json:"server_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	ReedId          string                 `protobuf:"bytes,3,opt,name=reed_id,json=reedID,proto3" json:"reed_id,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,5,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReedRemovalCert) Reset() {
	*x = ReedRemovalCert{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReedRemovalCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReedRemovalCert) ProtoMessage() {}

func (x *ReedRemovalCert) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReedRemovalCert.ProtoReflect.Descriptor instead.
func (*ReedRemovalCert) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ReedRemovalCert) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReedRemovalCert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReedRemovalCert) GetReedId() string {
	if x != nil {
		return x.ReedId
	}
	return ""
}

func (x *ReedRemovalCert) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ReedRemovalCert) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// Cryptographic certificate proving an account's removal, signed by
// both the removed user and their home server.
type AccountRemovalCert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverID,proto3" json:"server_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Note            string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,5,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountRemovalCert) Reset() {
	*x = AccountRemovalCert{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRemovalCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRemovalCert) ProtoMessage() {}

func (x *AccountRemovalCert) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRemovalCert.ProtoReflect.Descriptor instead.
func (*AccountRemovalCert) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *AccountRemovalCert) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AccountRemovalCert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountRemovalCert) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AccountRemovalCert) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *AccountRemovalCert) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// A user key's signed revocation: the revoked key's signature and its home
// server's countersignature. successor fields are set once a replacement
// key is uploaded and are covered by neither signature.
type KeyRevocationCert struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Successor          *string                `protobuf:"bytes,4,opt,name=successor,proto3,oneof" json:"successor,omitempty"`
	SuccessorSignature *string                `protobuf:"bytes,5,opt,name=successor_signature,json=successorSignature,proto3,oneof" json:"successor_signature,omitempty"`
	UserSignature      *UserSignature         `protobuf:"bytes,6,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature    *ServerSignature       `protobuf:"bytes,7,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyRevocationCert) Reset() {
	*x = KeyRevocationCert{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRevocationCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRevocationCert) ProtoMessage() {}

func (x *KeyRevocationCert) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRevocationCert.ProtoReflect.Descriptor instead.
func (*KeyRevocationCert) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *KeyRevocationCert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyRevocationCert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KeyRevocationCert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KeyRevocationCert) GetSuccessor() string {
	if x != nil && x.Successor != nil {
		return *x.Successor
	}
	return ""
}

func (x *KeyRevocationCert) GetSuccessorSignature() string {
	if x != nil && x.SuccessorSignature != nil {
		return *x.SuccessorSignature
	}
	return ""
}

func (x *KeyRevocationCert) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *KeyRevocationCert) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// A thread record: the author's ordered list of a thread's reeds.
type ThreadRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverID,proto3" json:"server_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	ThreadId        string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadID,proto3" json:"thread_id,omitempty"`
	ReedIds         []string               `protobuf:"bytes,4,rep,name=reed_ids,json=reedIDs,proto3" json:"reed_ids,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,5,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,6,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreadRecord) Reset() {
	*x = ThreadRecord{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRecord) ProtoMessage() {}

func (x *ThreadRecord) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRecord.ProtoReflect.Descriptor instead.
func (*ThreadRecord) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *ThreadRecord) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ThreadRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadRecord) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ThreadRecord) GetReedIds() []string {
	if x != nil {
		return x.ReedIds
	}
	return nil
}

func (x *ThreadRecord) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ThreadRecord) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

type ThreadRemovalCert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverID,proto3" json:"server_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	ThreadId        string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadID,proto3" json:"thread_id,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,5,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreadRemovalCert) Reset() {
	*x = ThreadRemovalCert{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadRemovalCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRemovalCert) ProtoMessage() {}

func (x *ThreadRemovalCert) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRemovalCert.ProtoReflect.Descriptor instead.
func (*ThreadRemovalCert) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *ThreadRemovalCert) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ThreadRemovalCert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadRemovalCert) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ThreadRemovalCert) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ThreadRemovalCert) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// A thread-removal certificate with the record it removes.
type ThreadRemoval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          *ThreadRemovalCert     `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Record        *ThreadRecord          `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadRemoval) Reset() {
	*x = ThreadRemoval{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadRemoval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRemoval) ProtoMessage() {}

func (x *ThreadRemoval) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRemoval.ProtoReflect.Descriptor instead.
func (*ThreadRemoval) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *ThreadRemoval) GetCert() *ThreadRemovalCert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *ThreadRemoval) GetRecord() *ThreadRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// A block: the blocking user's signature and their home server's
// countersignature.
type BlockCert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	BlockedUserId   string                 `protobuf:"bytes,2,opt,name=blocked_user_id,json=blockedUserID,proto3" json:"blocked_user_id,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,4,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockCert) Reset() {
	*x = BlockCert{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCert) ProtoMessage() {}

func (x *BlockCert) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCert.ProtoReflect.Descriptor instead.
func (*BlockCert) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *BlockCert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlockCert) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

func (x *BlockCert) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *BlockCert) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06syrinx\"5\n" +
	"\rUserSignature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05armor\x18\x02 \x01(\tR\x05armor\"U\n" +
	"\x0fServerSignature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05armor\x18\x02 \x01(\tR\x05armor\x12\x1c\n" +
	"\tsigned_at\x18\x03 \x01(\x03R\ttimestamp\"\x9b\x02\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12E\n" +
	"\x0faccount_removal\x18\x02 \x01(\v2\x1a.syrinx.AccountRemovalCertH\x00R\x0eaccountRemoval\x12<\n" +
	"\freed_removal\x18\x03 \x01(\v2\x17.syrinx.ReedRemovalCertH\x00R\vreedRemoval\x12>\n" +
	"\x0ethread_removal\x18\x04 \x01(\v2\x15.syrinx.ThreadRemovalH\x00R\rthreadRemoval\x12)\n" +
	"\x05block\x18\x05 \x01(\v2\x11.syrinx.BlockCertH\x00R\x05blockB\b\n" +
	"\x06detail\"\xdb\x02\n" +
	"\x06Ripple\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadID\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userID\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12$\n" +
	"\vreplying_to\x18\x05 \x01(\tH\x00R\n" +
	"replyingTo\x88\x01\x01\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12\x1b\n" +
	"\tposted_at\x18\a \x01(\x03R\bpostedAt\x12<\n" +
	"\x0euser_signature\x18\b \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\t \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignatureB\x0e\n" +
	"\f_replying_to\"\xe2\x01\n" +
	"\x0fReedRemovalCert\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverID\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x17\n" +
	"\areed_id\x18\x03 \x01(\tR\x06reedID\x12<\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x05 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"\xe0\x01\n" +
	"\x12AccountRemovalCert\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverID\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12<\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x05 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"\xd5\x02\n" +
	"\x11KeyRevocationCert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\tsuccessor\x18\x04 \x01(\tH\x00R\tsuccessor\x88\x01\x01\x124\n" +
	"\x13successor_signature\x18\x05 \x01(\tH\x01R\x12successorSignature\x88\x01\x01\x12<\n" +
	"\x0euser_signature\x18\x06 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\a \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignatureB\f\n" +
	"\n" +
	"_successorB\x16\n" +
	"\x14_successor_signature\"\xfe\x01\n" +
	"\fThreadRecord\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverID\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadID\x12\x19\n" +
	"\breed_ids\x18\x04 \x03(\tR\areedIDs\x12<\n" +
	"\x0euser_signature\x18\x05 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x06 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"\xe8\x01\n" +
	"\x11ThreadRemovalCert\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverID\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadID\x12<\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x05 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"l\n" +
	"\rThreadRemoval\x12-\n" +
	"\x04cert\x18\x01 \x01(\v2\x19.syrinx.ThreadRemovalCertR\x04cert\x12,\n" +
	"\x06record\x18\x02 \x01(\v2\x14.syrinx.ThreadRecordR\x06record\"\xce\x01\n" +
	"\tBlockCert\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userID\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\tR\rblockedUserID\x12<\n" +
	"\x0euser_signature\x18\x03 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x04 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignatureB Z\x1egithub.com/alvaro/syrinx/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_goTypes = []any{
	(*UserSignature)(nil),      // 0: syrinx.UserSignature
	(*ServerSignature)(nil),    // 1: syrinx.ServerSignature
	(*Error)(nil),              // 2: syrinx.Error
	(*Ripple)(nil),             // 3: syrinx.Ripple
	(*ReedRemovalCert)(nil),    // 4: syrinx.ReedRemovalCert
	(*AccountRemovalCert)(nil), // 5: syrinx.AccountRemovalCert
	(*KeyRevocationCert)(nil),  // 6: syrinx.KeyRevocationCert
	(*ThreadRecord)(nil),       // 7: syrinx.ThreadRecord
	(*ThreadRemovalCert)(nil),  // 8: syrinx.ThreadRemovalCert
	(*ThreadRemoval)(nil),      // 9: syrinx.ThreadRemoval
	(*BlockCert)(nil),          // 10: syrinx.BlockCert
}
var file_common_proto_depIdxs = []int32{
	5,  // 0: syrinx.Error.account_removal:type_name -> syrinx.AccountRemovalCert
	4,  // 1: syrinx.Error.reed_removal:type_name -> syrinx.ReedRemovalCert
	9,  // 2: syrinx.Error.thread_removal:type_name -> syrinx.ThreadRemoval
	10, // 3: syrinx.Error.block:type_name -> syrinx.BlockCert
	0,  // 4: syrinx.Ripple.user_signature:type_name -> syrinx.UserSignature
	1,  // 5: syrinx.Ripple.server_signature:type_name -> syrinx.ServerSignature
	0,  // 6: syrinx.ReedRemovalCert.user_signature:type_name -> syrinx.UserSignature
	1,  // 7: syrinx.ReedRemovalCert.server_signature:type_name -> syrinx.ServerSignature
	0,  // 8: syrinx.AccountRemovalCert.user_signature:type_name -> syrinx.UserSignature
	1,  // 9: syrinx.AccountRemovalCert.server_signature:type_name -> syrinx.ServerSignature
	0,  // 10: syrinx.KeyRevocationCert.user_signature:type_name -> syrinx.UserSignature
	1,  // 11: syrinx.KeyRevocationCert.server_signature:type_name -> syrinx.ServerSignature
	0,  // 12: syrinx.ThreadRecord.user_signature:type_name -> syrinx.UserSignature
	1,  // 13: syrinx.ThreadRecord.server_signature:type_name -> syrinx.ServerSignature
	0,  // 14: syrinx.ThreadRemovalCert.user_signature:type_name -> syrinx.UserSignature
	1,  // 15: syrinx.ThreadRemovalCert.server_signature:type_name -> syrinx.ServerSignature
	8,  // 16: syrinx.ThreadRemoval.cert:type_name -> syrinx.ThreadRemovalCert
	7,  // 17: syrinx.ThreadRemoval.record:type_name -> syrinx.ThreadRecord
	0,  // 18: syrinx.BlockCert.user_signature:type_name -> syrinx.UserSignature
	1,  // 19: syrinx.BlockCert.server_signature:type_name -> syrinx.ServerSignature
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[2].OneofWrappers = []any{
		(*Error_AccountRemoval)(nil),
		(*Error_ReedRemoval)(nil),
		(*Error_ThreadRemoval)(nil),
		(*Error_Block)(nil),
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
