// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GET /server/info.
type ServerInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RecoveryMode bool                   `protobuf:"varint,3,opt,name=recovery_mode,json=recoveryMode,proto3" json:"recovery_mode,omitempty"`
	SignupMode   string                 `protobuf:"bytes,4,opt,name=signup_mode,json=signupMode,proto3" json:"signup_mode,omitempty"`
	// -1 = unlimited.
	MaxInvitesPerUser int32 `protobuf:"varint,5,opt,name=max_invites_per_user,json=maxInvitesPerUser,proto3" json:"max_invites_per_user,omitempty"`
	// This server's current signing key id (fingerprint@serverID).
	ServerKeyId   string                 `protobuf:"bytes,6,opt,name=server_key_id,json=serverKeyId,proto3" json:"server_key_id,omitempty"`
	Federation    []*FederatedServerInfo `protobuf:"bytes,7,rep,name=federation,proto3" json:"federation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetRecoveryMode() bool {
	if x != nil {
		return x.RecoveryMode
	}
	return false
}

func (x *ServerInfo) GetSignupMode() string {
	if x != nil {
		return x.SignupMode
	}
	return ""
}

func (x *ServerInfo) GetMaxInvitesPerUser() int32 {
	if x != nil {
		return x.MaxInvitesPerUser
	}
	return 0
}

func (x *ServerInfo) GetServerKeyId() string {
	if x != nil {
		return x.ServerKeyId
	}
	return ""
}

func (x *ServerInfo) GetFederation() []*FederatedServerInfo {
	if x != nil {
		return x.Federation
	}
	return nil
}

// One established peer, for picking which server a verification link opens on.
type FederatedServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FrontendUrl   string                 `protobuf:"bytes,5,opt,name=frontend_url,json=frontendUrl,proto3" json:"frontend_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederatedServerInfo) Reset() {
	*x = FederatedServerInfo{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedServerInfo) ProtoMessage() {}

func (x *FederatedServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedServerInfo.ProtoReflect.Descriptor instead.
func (*FederatedServerInfo) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *FederatedServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FederatedServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FederatedServerInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *FederatedServerInfo) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FederatedServerInfo) GetFrontendUrl() string {
	if x != nil {
		return x.FrontendUrl
	}
	return ""
}

// GET /users/id: a fresh user id and this server's signature over it.
type UserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResponse) Reset() {
	*x = UserIDResponse{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResponse) ProtoMessage() {}

func (x *UserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResponse.ProtoReflect.Descriptor instead.
func (*UserIDResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *UserIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserIDResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserIDResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// POST /check-username and /users/me/check-username.
type CheckUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	InviteId      string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteID,proto3" json:"invite_id,omitempty"`
	InviteSecret  string                 `protobuf:"bytes,3,opt,name=invite_secret,json=inviteSecret,proto3" json:"invite_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameRequest) Reset() {
	*x = CheckUsernameRequest{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameRequest) ProtoMessage() {}

func (x *CheckUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CheckUsernameRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *CheckUsernameRequest) GetInviteSecret() string {
	if x != nil {
		return x.InviteSecret
	}
	return ""
}

type SignupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey         string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature         string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	UserSignature     string                 `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	UserId            string                 `protobuf:"bytes,5,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	UserIdSignature   string                 `protobuf:"bytes,6,opt,name=user_id_signature,json=userIDSignature,proto3" json:"user_id_signature,omitempty"`
	UserIdFingerprint string                 `protobuf:"bytes,7,opt,name=user_id_fingerprint,json=userIDFingerprint,proto3" json:"user_id_fingerprint,omitempty"`
	InviteId          string                 `protobuf:"bytes,8,opt,name=invite_id,json=inviteID,proto3" json:"invite_id,omitempty"`
	InviteSecret      string                 `protobuf:"bytes,9,opt,name=invite_secret,json=inviteSecret,proto3" json:"invite_secret,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *SignupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignupRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignupRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignupRequest) GetUserSignature() string {
	if x != nil {
		return x.UserSignature
	}
	return ""
}

func (x *SignupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignupRequest) GetUserIdSignature() string {
	if x != nil {
		return x.UserIdSignature
	}
	return ""
}

func (x *SignupRequest) GetUserIdFingerprint() string {
	if x != nil {
		return x.UserIdFingerprint
	}
	return ""
}

func (x *SignupRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *SignupRequest) GetInviteSecret() string {
	if x != nil {
		return x.InviteSecret
	}
	return ""
}

// The invite a user redeemed, nested on their identity record. id is the
// invite's id; user_id/username identify the inviter for display.
type UserInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInvite) Reset() {
	*x = UserInvite{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInvite) ProtoMessage() {}

func (x *UserInvite) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInvite.ProtoReflect.Descriptor instead.
func (*UserInvite) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *UserInvite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInvite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInvite) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// A signed identity record (GET /users/{id}/profile).
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role            string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Bio             string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	MemberSince     uint32                 `protobuf:"varint,5,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,6,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,7,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	Invite          *UserInvite            `protobuf:"bytes,8,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetMemberSince() uint32 {
	if x != nil {
		return x.MemberSince
	}
	return 0
}

func (x *User) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *User) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *User) GetInvite() *UserInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

// The unsigned, frequently changing view of a user (GET /users/{id}/info).
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Oldest surviving reed by this user; unset when they have none.
	FirstReedId    *string `protobuf:"bytes,2,opt,name=first_reed_id,json=firstReedId,proto3,oneof" json:"first_reed_id,omitempty"`
	FollowersCount int32   `protobuf:"varint,3,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount int32   `protobuf:"varint,4,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	ActiveKeyId    string  `protobuf:"bytes,5,opt,name=active_key_id,json=activeKeyID,proto3" json:"active_key_id,omitempty"`
	// Same instant as the profile's server_signature.signed_at.
	ProfileTimestamp uint32   `protobuf:"varint,6,opt,name=profile_timestamp,json=profileTimestamp,proto3" json:"profile_timestamp,omitempty"`
	PinnedReedIds    []string `protobuf:"bytes,7,rep,name=pinned_reed_ids,json=pinnedReedIDs,proto3" json:"pinned_reed_ids,omitempty"`
	VouchIds         []string `protobuf:"bytes,8,rep,name=vouch_ids,json=vouchIDs,proto3" json:"vouch_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetFirstReedId() string {
	if x != nil && x.FirstReedId != nil {
		return *x.FirstReedId
	}
	return ""
}

func (x *UserInfo) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *UserInfo) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *UserInfo) GetActiveKeyId() string {
	if x != nil {
		return x.ActiveKeyId
	}
	return ""
}

func (x *UserInfo) GetProfileTimestamp() uint32 {
	if x != nil {
		return x.ProfileTimestamp
	}
	return 0
}

func (x *UserInfo) GetPinnedReedIds() []string {
	if x != nil {
		return x.PinnedReedIds
	}
	return nil
}

func (x *UserInfo) GetVouchIds() []string {
	if x != nil {
		return x.VouchIds
	}
	return nil
}

// PUT /users/me: a full replacement of the user-authored fields.
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	UserSignature string                 `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetUserSignature() string {
	if x != nil {
		return x.UserSignature
	}
	return ""
}

// DELETE /users/me.
type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *DeleteAccountRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type UserSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearchResult) Reset() {
	*x = UserSearchResult{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchResult) ProtoMessage() {}

func (x *UserSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchResult.ProtoReflect.Descriptor instead.
func (*UserSearchResult) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *UserSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSearchResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSearchResult) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type UserSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSearchResult    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearchResponse) Reset() {
	*x = UserSearchResponse{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchResponse) ProtoMessage() {}

func (x *UserSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchResponse.ProtoReflect.Descriptor instead.
func (*UserSearchResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *UserSearchResponse) GetUsers() []*UserSearchResult {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserSearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *UserSearchResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// POST/DELETE /users/{id}/follow. follower_id is read only when a peer
// relays the follow for one of its users.
type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerID,proto3" json:"follower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *FollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

type FollowListUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	FollowedAt    uint32                 `protobuf:"varint,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListUser) Reset() {
	*x = FollowListUser{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListUser) ProtoMessage() {}

func (x *FollowListUser) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListUser.ProtoReflect.Descriptor instead.
func (*FollowListUser) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *FollowListUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowListUser) GetFollowedAt() uint32 {
	if x != nil {
		return x.FollowedAt
	}
	return 0
}

type FollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*FollowListUser      `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListResponse) Reset() {
	*x = FollowListResponse{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResponse) ProtoMessage() {}

func (x *FollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResponse.ProtoReflect.Descriptor instead.
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *FollowListResponse) GetUsers() []*FollowListUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FollowListResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// A distributed user or server public key.
type PublicKey struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Armor     string                 `protobuf:"bytes,3,opt,name=armor,proto3" json:"armor,omitempty"`
	CreatedAt uint32                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Revoked   bool                   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// The replaced key's id; unset for a signup key.
	Predecessor     *string          `protobuf:"bytes,6,opt,name=predecessor,proto3,oneof" json:"predecessor,omitempty"`
	ServerSignature *ServerSignature `protobuf:"bytes,7,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	// Set on revoked server keys only.
	RevokedAt     uint32 `protobuf:"varint,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Compromised   bool   `protobuf:"varint,9,opt,name=compromised,proto3" json:"compromised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *PublicKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PublicKey) GetArmor() string {
	if x != nil {
		return x.Armor
	}
	return ""
}

func (x *PublicKey) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PublicKey) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *PublicKey) GetPredecessor() string {
	if x != nil && x.Predecessor != nil {
		return *x.Predecessor
	}
	return ""
}

func (x *PublicKey) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *PublicKey) GetRevokedAt() uint32 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *PublicKey) GetCompromised() bool {
	if x != nil {
		return x.Compromised
	}
	return false
}

// POST /keys: revokes the predecessor key and registers the new one.
type AddPublicKeyRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  string                 `protobuf:"bytes,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	PublicKey               string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RevokedKeyFingerprint   string                 `protobuf:"bytes,3,opt,name=revoked_key_fingerprint,json=revokedKeyFingerprint,proto3" json:"revoked_key_fingerprint,omitempty"`
	RevokedKeySignature     string                 `protobuf:"bytes,4,opt,name=revoked_key_signature,json=revokedKeySignature,proto3" json:"revoked_key_signature,omitempty"`
	NewKeySignature         string                 `protobuf:"bytes,5,opt,name=new_key_signature,json=newKeySignature,proto3" json:"new_key_signature,omitempty"`
	RevocationReason        string                 `protobuf:"bytes,6,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	RevocationUserSignature string                 `protobuf:"bytes,7,opt,name=revocation_user_signature,json=revocationUserSignature,proto3" json:"revocation_user_signature,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AddPublicKeyRequest) Reset() {
	*x = AddPublicKeyRequest{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublicKeyRequest) ProtoMessage() {}

func (x *AddPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AddPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *AddPublicKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPublicKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddPublicKeyRequest) GetRevokedKeyFingerprint() string {
	if x != nil {
		return x.RevokedKeyFingerprint
	}
	return ""
}

func (x *AddPublicKeyRequest) GetRevokedKeySignature() string {
	if x != nil {
		return x.RevokedKeySignature
	}
	return ""
}

func (x *AddPublicKeyRequest) GetNewKeySignature() string {
	if x != nil {
		return x.NewKeySignature
	}
	return ""
}

func (x *AddPublicKeyRequest) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *AddPublicKeyRequest) GetRevocationUserSignature() string {
	if x != nil {
		return x.RevocationUserSignature
	}
	return ""
}

// A server key's retirement in favour of its successor, signed by both.
type ServerKeyRevocation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerId           string                 `protobuf:"bytes,1,opt,name=server_id,json=serverID,proto3" json:"server_id,omitempty"`
	KeyId              string                 `protobuf:"bytes,2,opt,name=key_id,json=keyID,proto3" json:"key_id,omitempty"`
	Successor          string                 `protobuf:"bytes,3,opt,name=successor,proto3" json:"successor,omitempty"`
	Compromised        bool                   `protobuf:"varint,4,opt,name=compromised,proto3" json:"compromised,omitempty"`
	Reason             string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	SignedAt           uint32                 `protobuf:"varint,6,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	Signature          string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	SuccessorSignature string                 `protobuf:"bytes,8,opt,name=successor_signature,json=successorSignature,proto3" json:"successor_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerKeyRevocation) Reset() {
	*x = ServerKeyRevocation{}
	mi := &file_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKeyRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKeyRevocation) ProtoMessage() {}

func (x *ServerKeyRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKeyRevocation.ProtoReflect.Descriptor instead.
func (*ServerKeyRevocation) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{17}
}

func (x *ServerKeyRevocation) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerKeyRevocation) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ServerKeyRevocation) GetSuccessor() string {
	if x != nil {
		return x.Successor
	}
	return ""
}

func (x *ServerKeyRevocation) GetCompromised() bool {
	if x != nil {
		return x.Compromised
	}
	return false
}

func (x *ServerKeyRevocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServerKeyRevocation) GetSignedAt() uint32 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

func (x *ServerKeyRevocation) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ServerKeyRevocation) GetSuccessorSignature() string {
	if x != nil {
		return x.SuccessorSignature
	}
	return ""
}

// GET /keys/{id}/revocation: a user key's or a server key's revocation.
type KeyRevocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Revocation:
	//
	//	*KeyRevocationResponse_User
	//	*KeyRevocationResponse_Server
	Revocation    isKeyRevocationResponse_Revocation `protobuf_oneof:"revocation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRevocationResponse) Reset() {
	*x = KeyRevocationResponse{}
	mi := &file_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRevocationResponse) ProtoMessage() {}

func (x *KeyRevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRevocationResponse.ProtoReflect.Descriptor instead.
func (*KeyRevocationResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{18}
}

func (x *KeyRevocationResponse) GetRevocation() isKeyRevocationResponse_Revocation {
	if x != nil {
		return x.Revocation
	}
	return nil
}

func (x *KeyRevocationResponse) GetUser() *KeyRevocationCert {
	if x != nil {
		if x, ok := x.Revocation.(*KeyRevocationResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *KeyRevocationResponse) GetServer() *ServerKeyRevocation {
	if x != nil {
		if x, ok := x.Revocation.(*KeyRevocationResponse_Server); ok {
			return x.Server
		}
	}
	return nil
}

type isKeyRevocationResponse_Revocation interface {
	isKeyRevocationResponse_Revocation()
}

type KeyRevocationResponse_User struct {
	User *KeyRevocationCert `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type KeyRevocationResponse_Server struct {
	Server *ServerKeyRevocation `protobuf:"bytes,2,opt,name=server,proto3,oneof"`
}

func (*KeyRevocationResponse_User) isKeyRevocationResponse_Revocation() {}

func (*KeyRevocationResponse_Server) isKeyRevocationResponse_Revocation() {}

// POST /users/me/backup.
type RecordBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBackupRequest) Reset() {
	*x = RecordBackupRequest{}
	mi := &file_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBackupRequest) ProtoMessage() {}

func (x *RecordBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBackupRequest.ProtoReflect.Descriptor instead.
func (*RecordBackupRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{19}
}

func (x *RecordBackupRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// POST /users/device: the device id now bound.
type BindDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindDeviceResponse) Reset() {
	*x = BindDeviceResponse{}
	mi := &file_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindDeviceResponse) ProtoMessage() {}

func (x *BindDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindDeviceResponse.ProtoReflect.Descriptor instead.
func (*BindDeviceResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{20}
}

func (x *BindDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// POST /users/{id}/block.
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{21}
}

func (x *BlockRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BlockRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type BlockListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockCert           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockListResponse) Reset() {
	*x = BlockListResponse{}
	mi := &file_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockListResponse) ProtoMessage() {}

func (x *BlockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockListResponse.ProtoReflect.Descriptor instead.
func (*BlockListResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{22}
}

func (x *BlockListResponse) GetBlocks() []*BlockCert {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// A signed vouch: one user attesting they compared fingerprints and the
// subject holds that exact key.
type Vouch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VoucherUserId   string                 `protobuf:"bytes,2,opt,name=voucher_user_id,json=voucherUserID,proto3" json:"voucher_user_id,omitempty"`
	VoucherKeyId    string                 `protobuf:"bytes,3,opt,name=voucher_key_id,json=voucherKeyID,proto3" json:"voucher_key_id,omitempty"`
	SubjectUserId   string                 `protobuf:"bytes,4,opt,name=subject_user_id,json=subjectUserID,proto3" json:"subject_user_id,omitempty"`
	SubjectKeyId    string                 `protobuf:"bytes,5,opt,name=subject_key_id,json=subjectKeyID,proto3" json:"subject_key_id,omitempty"`
	Note            string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,7,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,8,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	// Set only on a retracted vouch; its presence is the withdrawal.
	Withdrawal    *VouchWithdrawal `protobuf:"bytes,9,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vouch) Reset() {
	*x = Vouch{}
	mi := &file_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vouch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vouch) ProtoMessage() {}

func (x *Vouch) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vouch.ProtoReflect.Descriptor instead.
func (*Vouch) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{23}
}

func (x *Vouch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vouch) GetVoucherUserId() string {
	if x != nil {
		return x.VoucherUserId
	}
	return ""
}

func (x *Vouch) GetVoucherKeyId() string {
	if x != nil {
		return x.VoucherKeyId
	}
	return ""
}

func (x *Vouch) GetSubjectUserId() string {
	if x != nil {
		return x.SubjectUserId
	}
	return ""
}

func (x *Vouch) GetSubjectKeyId() string {
	if x != nil {
		return x.SubjectKeyId
	}
	return ""
}

func (x *Vouch) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Vouch) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *Vouch) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *Vouch) GetWithdrawal() *VouchWithdrawal {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type VouchWithdrawal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserSignature   *UserSignature         `protobuf:"bytes,1,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,2,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VouchWithdrawal) Reset() {
	*x = VouchWithdrawal{}
	mi := &file_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchWithdrawal) ProtoMessage() {}

func (x *VouchWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VouchWithdrawal.ProtoReflect.Descriptor instead.
func (*VouchWithdrawal) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{24}
}

func (x *VouchWithdrawal) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *VouchWithdrawal) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

type VouchListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vouches       []*Vouch               `protobuf:"bytes,1,rep,name=vouches,proto3" json:"vouches,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VouchListResponse) Reset() {
	*x = VouchListResponse{}
	mi := &file_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchListResponse) ProtoMessage() {}

func (x *VouchListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VouchListResponse.ProtoReflect.Descriptor instead.
func (*VouchListResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{25}
}

func (x *VouchListResponse) GetVouches() []*Vouch {
	if x != nil {
		return x.Vouches
	}
	return nil
}

func (x *VouchListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// POST /vouches. voucher_id is read only when a peer relays the request.
type CreateVouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKeyId  string                 `protobuf:"bytes,1,opt,name=subject_key_id,json=subjectKeyID,proto3" json:"subject_key_id,omitempty"`
	VoucherKeyId  string                 `protobuf:"bytes,2,opt,name=voucher_key_id,json=voucherKeyID,proto3" json:"voucher_key_id,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	VoucherId     string                 `protobuf:"bytes,5,opt,name=voucher_id,json=voucherID,proto3" json:"voucher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVouchRequest) Reset() {
	*x = CreateVouchRequest{}
	mi := &file_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVouchRequest) ProtoMessage() {}

func (x *CreateVouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVouchRequest.ProtoReflect.Descriptor instead.
func (*CreateVouchRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{26}
}

func (x *CreateVouchRequest) GetSubjectKeyId() string {
	if x != nil {
		return x.SubjectKeyId
	}
	return ""
}

func (x *CreateVouchRequest) GetVoucherKeyId() string {
	if x != nil {
		return x.VoucherKeyId
	}
	return ""
}

func (x *CreateVouchRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateVouchRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateVouchRequest) GetVoucherId() string {
	if x != nil {
		return x.VoucherId
	}
	return ""
}

// DELETE /vouches/{subjectKeyID}.
type WithdrawVouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoucherKeyId  string                 `protobuf:"bytes,1,opt,name=voucher_key_id,json=voucherKeyID,proto3" json:"voucher_key_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	VoucherId     string                 `protobuf:"bytes,3,opt,name=voucher_id,json=voucherID,proto3" json:"voucher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawVouchRequest) Reset() {
	*x = WithdrawVouchRequest{}
	mi := &file_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawVouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawVouchRequest) ProtoMessage() {}

func (x *WithdrawVouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawVouchRequest.ProtoReflect.Descriptor instead.
func (*WithdrawVouchRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{27}
}

func (x *WithdrawVouchRequest) GetVoucherKeyId() string {
	if x != nil {
		return x.VoucherKeyId
	}
	return ""
}

func (x *WithdrawVouchRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WithdrawVouchRequest) GetVoucherId() string {
	if x != nil {
		return x.VoucherId
	}
	return ""
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\x06syrinx\x1a\fcommon.proto\"\x88\x02\n" +
	"\n" +
	"ServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rrecovery_mode\x18\x03 \x01(\bR\frecoveryMode\x12\x1f\n" +
	"\vsignup_mode\x18\x04 \x01(\tR\n" +
	"signupMode\x12/\n" +
	"\x14max_invites_per_user\x18\x05 \x01(\x05R\x11maxInvitesPerUser\x12\"\n" +
	"\rserver_key_id\x18\x06 \x01(\tR\vserverKeyId\x12;\n" +
	"\n" +
	"federation\x18\a \x03(\v2\x1b.syrinx.FederatedServerInfoR\n" +
	"federation\"\x92\x01\n" +
	"\x13FederatedServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\rR\tcreatedAt\x12!\n" +
	"\ffrontend_url\x18\x05 \x01(\tR\vfrontendUrl\"i\n" +
	"\x0eUserIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userID\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\"t\n" +
	"\x14CheckUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tinvite_id\x18\x02 \x01(\tR\binviteID\x12#\n" +
	"\rinvite_secret\x18\x03 \x01(\tR\finviteSecret\"\xc6\x02\n" +
	"\rSignupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12%\n" +
	"\x0euser_signature\x18\x04 \x01(\tR\ruserSignature\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userID\x12*\n" +
	"\x11user_id_signature\x18\x06 \x01(\tR\x0fuserIDSignature\x12.\n" +
	"\x13user_id_fingerprint\x18\a \x01(\tR\x11userIDFingerprint\x12\x1b\n" +
	"\tinvite_id\x18\b \x01(\tR\binviteID\x12#\n" +
	"\rinvite_secret\x18\t \x01(\tR\finviteSecret\"Q\n" +
	"\n" +
	"UserInvite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\xa9\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12!\n" +
	"\fmember_since\x18\x05 \x01(\rR\vmemberSince\x12<\n" +
	"\x0euser_signature\x18\x06 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\a \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\x12*\n" +
	"\x06invite\x18\b \x01(\v2\x12.syrinx.UserInviteR\x06invite\"\xbd\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\rfirst_reed_id\x18\x02 \x01(\tH\x00R\vfirstReedId\x88\x01\x01\x12'\n" +
	"\x0ffollowers_count\x18\x03 \x01(\x05R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\x04 \x01(\x05R\x0efollowingCount\x12\"\n" +
	"\ractive_key_id\x18\x05 \x01(\tR\vactiveKeyID\x12+\n" +
	"\x11profile_timestamp\x18\x06 \x01(\rR\x10profileTimestamp\x12&\n" +
	"\x0fpinned_reed_ids\x18\a \x03(\tR\rpinnedReedIDs\x12\x1b\n" +
	"\tvouch_ids\x18\b \x03(\tR\bvouchIDsB\x10\n" +
	"\x0e_first_reed_id\"h\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\tR\ruserSignature\"H\n" +
	"\x14DeleteAccountRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"_\n" +
	"\x10UserSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\"\x80\x01\n" +
	"\x12UserSearchResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.syrinx.UserSearchResultR\x05users\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"0\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerID\"J\n" +
	"\x0eFollowListUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userID\x12\x1f\n" +
	"\vfollowed_at\x18\x02 \x01(\rR\n" +
	"followedAt\"]\n" +
	"\x12FollowListResponse\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.syrinx.FollowListUserR\x05users\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xbf\x02\n" +
	"\tPublicKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x14\n" +
	"\x05armor\x18\x03 \x01(\tR\x05armor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\rR\tcreatedAt\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\x12%\n" +
	"\vpredecessor\x18\x06 \x01(\tH\x00R\vpredecessor\x88\x01\x01\x12B\n" +
	"\x10server_signature\x18\a \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\b \x01(\rR\trevokedAt\x12 \n" +
	"\vcompromised\x18\t \x01(\bR\vcompromisedB\x0e\n" +
	"\f_predecessor\"\xce\x02\n" +
	"\x13AddPublicKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userID\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x126\n" +
	"\x17revoked_key_fingerprint\x18\x03 \x01(\tR\x15revokedKeyFingerprint\x122\n" +
	"\x15revoked_key_signature\x18\x04 \x01(\tR\x13revokedKeySignature\x12*\n" +
	"\x11new_key_signature\x18\x05 \x01(\tR\x0fnewKeySignature\x12+\n" +
	"\x11revocation_reason\x18\x06 \x01(\tR\x10revocationReason\x12:\n" +
	"\x19revocation_user_signature\x18\a \x01(\tR\x17revocationUserSignature\"\x8d\x02\n" +
	"\x13ServerKeyRevocation\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverID\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyID\x12\x1c\n" +
	"\tsuccessor\x18\x03 \x01(\tR\tsuccessor\x12 \n" +
	"\vcompromised\x18\x04 \x01(\bR\vcompromised\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1b\n" +
	"\tsigned_at\x18\x06 \x01(\rR\bsignedAt\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12/\n" +
	"\x13successor_signature\x18\b \x01(\tR\x12successorSignature\"\x8d\x01\n" +
	"\x15KeyRevocationResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x19.syrinx.KeyRevocationCertH\x00R\x04user\x125\n" +
	"\x06server\x18\x02 \x01(\v2\x1b.syrinx.ServerKeyRevocationH\x00R\x06serverB\f\n" +
	"\n" +
	"revocation\")\n" +
	"\x13RecordBackupRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"1\n" +
	"\x12BindDeviceResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"N\n" +
	"\fBlockRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\">\n" +
	"\x11BlockListResponse\x12)\n" +
	"\x06blocks\x18\x01 \x03(\v2\x11.syrinx.BlockCertR\x06blocks\"\x82\x03\n" +
	"\x05Vouch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fvoucher_user_id\x18\x02 \x01(\tR\rvoucherUserID\x12$\n" +
	"\x0evoucher_key_id\x18\x03 \x01(\tR\fvoucherKeyID\x12&\n" +
	"\x0fsubject_user_id\x18\x04 \x01(\tR\rsubjectUserID\x12$\n" +
	"\x0esubject_key_id\x18\x05 \x01(\tR\fsubjectKeyID\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12<\n" +
	"\x0euser_signature\x18\a \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\b \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\x127\n" +
	"\n" +
	"withdrawal\x18\t \x01(\v2\x17.syrinx.VouchWithdrawalR\n" +
	"withdrawal\"\x93\x01\n" +
	"\x0fVouchWithdrawal\x12<\n" +
	"\x0euser_signature\x18\x01 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x02 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"]\n" +
	"\x11VouchListResponse\x12'\n" +
	"\avouches\x18\x01 \x03(\v2\r.syrinx.VouchR\avouches\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xb1\x01\n" +
	"\x12CreateVouchRequest\x12$\n" +
	"\x0esubject_key_id\x18\x01 \x01(\tR\fsubjectKeyID\x12$\n" +
	"\x0evoucher_key_id\x18\x02 \x01(\tR\fvoucherKeyID\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"voucher_id\x18\x05 \x01(\tR\tvoucherID\"y\n" +
	"\x14WithdrawVouchRequest\x12$\n" +
	"\x0evoucher_key_id\x18\x01 \x01(\tR\fvoucherKeyID\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"voucher_id\x18\x03 \x01(\tR\tvoucherIDB Z\x1egithub.com/alvaro/syrinx/protob\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_identity_proto_goTypes = []any{
	(*ServerInfo)(nil),            // 0: syrinx.ServerInfo
	(*FederatedServerInfo)(nil),   // 1: syrinx.FederatedServerInfo
	(*UserIDResponse)(nil),        // 2: syrinx.UserIDResponse
	(*CheckUsernameRequest)(nil),  // 3: syrinx.CheckUsernameRequest
	(*SignupRequest)(nil),         // 4: syrinx.SignupRequest
	(*UserInvite)(nil),            // 5: syrinx.UserInvite
	(*User)(nil),                  // 6: syrinx.User
	(*UserInfo)(nil),              // 7: syrinx.UserInfo
	(*UpdateUserRequest)(nil),     // 8: syrinx.UpdateUserRequest
	(*DeleteAccountRequest)(nil),  // 9: syrinx.DeleteAccountRequest
	(*UserSearchResult)(nil),      // 10: syrinx.UserSearchResult
	(*UserSearchResponse)(nil),    // 11: syrinx.UserSearchResponse
	(*FollowRequest)(nil),         // 12: syrinx.FollowRequest
	(*FollowListUser)(nil),        // 13: syrinx.FollowListUser
	(*FollowListResponse)(nil),    // 14: syrinx.FollowListResponse
	(*PublicKey)(nil),             // 15: syrinx.PublicKey
	(*AddPublicKeyRequest)(nil),   // 16: syrinx.AddPublicKeyRequest
	(*ServerKeyRevocation)(nil),   // 17: syrinx.ServerKeyRevocation
	(*KeyRevocationResponse)(nil), // 18: syrinx.KeyRevocationResponse
	(*RecordBackupRequest)(nil),   // 19: syrinx.RecordBackupRequest
	(*BindDeviceResponse)(nil),    // 20: syrinx.BindDeviceResponse
	(*BlockRequest)(nil),          // 21: syrinx.BlockRequest
	(*BlockListResponse)(nil),     // 22: syrinx.BlockListResponse
	(*Vouch)(nil),                 // 23: syrinx.Vouch
	(*VouchWithdrawal)(nil),       // 24: syrinx.VouchWithdrawal
	(*VouchListResponse)(nil),     // 25: syrinx.VouchListResponse
	(*CreateVouchRequest)(nil),    // 26: syrinx.CreateVouchRequest
	(*WithdrawVouchRequest)(nil),  // 27: syrinx.WithdrawVouchRequest
	(*UserSignature)(nil),         // 28: syrinx.UserSignature
	(*ServerSignature)(nil),       // 29: syrinx.ServerSignature
	(*KeyRevocationCert)(nil),     // 30: syrinx.KeyRevocationCert
	(*BlockCert)(nil),             // 31: syrinx.BlockCert
}
var file_identity_proto_depIdxs = []int32{
	1,  // 0: syrinx.ServerInfo.federation:type_name -> syrinx.FederatedServerInfo
	28, // 1: syrinx.User.user_signature:type_name -> syrinx.UserSignature
	29, // 2: syrinx.User.server_signature:type_name -> syrinx.ServerSignature
	5,  // 3: syrinx.User.invite:type_name -> syrinx.UserInvite
	10, // 4: syrinx.UserSearchResponse.users:type_name -> syrinx.UserSearchResult
	13, // 5: syrinx.FollowListResponse.users:type_name -> syrinx.FollowListUser
	29, // 6: syrinx.PublicKey.server_signature:type_name -> syrinx.ServerSignature
	30, // 7: syrinx.KeyRevocationResponse.user:type_name -> syrinx.KeyRevocationCert
	17, // 8: syrinx.KeyRevocationResponse.server:type_name -> syrinx.ServerKeyRevocation
	31, // 9: syrinx.BlockListResponse.blocks:type_name -> syrinx.BlockCert
	28, // 10: syrinx.Vouch.user_signature:type_name -> syrinx.UserSignature
	29, // 11: syrinx.Vouch.server_signature:type_name -> syrinx.ServerSignature
	24, // 12: syrinx.Vouch.withdrawal:type_name -> syrinx.VouchWithdrawal
	28, // 13: syrinx.VouchWithdrawal.user_signature:type_name -> syrinx.UserSignature
	29, // 14: syrinx.VouchWithdrawal.server_signature:type_name -> syrinx.ServerSignature
	23, // 15: syrinx.VouchListResponse.vouches:type_name -> syrinx.Vouch
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	file_common_proto_init()
	file_identity_proto_msgTypes[7].OneofWrappers = []any{}
	file_identity_proto_msgTypes[15].OneofWrappers = []any{}
	file_identity_proto_msgTypes[18].OneofWrappers = []any{
		(*KeyRevocationResponse_User)(nil),
		(*KeyRevocationResponse_Server)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
