// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: recovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single-use challenge nonce, for account recovery and identity claims.
type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

// POST /account-recovery/bootstrap.
type AccountRecoveryBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyID,proto3" json:"key_id,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRecoveryBootstrapRequest) Reset() {
	*x = AccountRecoveryBootstrapRequest{}
	mi := &file_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRecoveryBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRecoveryBootstrapRequest) ProtoMessage() {}

func (x *AccountRecoveryBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRecoveryBootstrapRequest.ProtoReflect.Descriptor instead.
func (*AccountRecoveryBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *AccountRecoveryBootstrapRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AccountRecoveryBootstrapRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountRecoveryBootstrapRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AccountRecoveryBootstrapRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AccountRecoveryBootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *User                  `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Following     []string               `protobuf:"bytes,2,rep,name=following,proto3" json:"following,omitempty"`
	TipReedId     *string                `protobuf:"bytes,3,opt,name=tip_reed_id,json=tipReedID,proto3,oneof" json:"tip_reed_id,omitempty"`
	ReedIds       []string               `protobuf:"bytes,4,rep,name=reed_ids,json=reedIDs,proto3" json:"reed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRecoveryBootstrapResponse) Reset() {
	*x = AccountRecoveryBootstrapResponse{}
	mi := &file_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRecoveryBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRecoveryBootstrapResponse) ProtoMessage() {}

func (x *AccountRecoveryBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRecoveryBootstrapResponse.ProtoReflect.Descriptor instead.
func (*AccountRecoveryBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *AccountRecoveryBootstrapResponse) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AccountRecoveryBootstrapResponse) GetFollowing() []string {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *AccountRecoveryBootstrapResponse) GetTipReedId() string {
	if x != nil && x.TipReedId != nil {
		return *x.TipReedId
	}
	return ""
}

func (x *AccountRecoveryBootstrapResponse) GetReedIds() []string {
	if x != nil {
		return x.ReedIds
	}
	return nil
}

// A countersigned identity record as recovery's claim, peer and status
// flows carry it: User plus the active key and whether reeds exist.
type RecoveryProfile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role                 string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	MemberSince          uint32                 `protobuf:"varint,4,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	Bio                  string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	ActiveKeyFingerprint string                 `protobuf:"bytes,6,opt,name=active_key_fingerprint,json=activeKeyFingerprint,proto3" json:"active_key_fingerprint,omitempty"`
	UserSignature        *UserSignature         `protobuf:"bytes,7,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature      *ServerSignature       `protobuf:"bytes,8,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	HasReeds             bool                   `protobuf:"varint,9,opt,name=has_reeds,json=hasReeds,proto3" json:"has_reeds,omitempty"`
	Invite               *UserInvite            `protobuf:"bytes,10,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecoveryProfile) Reset() {
	*x = RecoveryProfile{}
	mi := &file_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryProfile) ProtoMessage() {}

func (x *RecoveryProfile) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryProfile.ProtoReflect.Descriptor instead.
func (*RecoveryProfile) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *RecoveryProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecoveryProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RecoveryProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RecoveryProfile) GetMemberSince() uint32 {
	if x != nil {
		return x.MemberSince
	}
	return 0
}

func (x *RecoveryProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *RecoveryProfile) GetActiveKeyFingerprint() string {
	if x != nil {
		return x.ActiveKeyFingerprint
	}
	return ""
}

func (x *RecoveryProfile) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *RecoveryProfile) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *RecoveryProfile) GetHasReeds() bool {
	if x != nil {
		return x.HasReeds
	}
	return false
}

func (x *RecoveryProfile) GetInvite() *UserInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

// POST /users/status: complete, unknown or ongoing, also on 404 and 409.
type UserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *UserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecoveryRevocation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint     string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Successor       *string                `protobuf:"bytes,4,opt,name=successor,proto3,oneof" json:"successor,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,5,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,6,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecoveryRevocation) Reset() {
	*x = RecoveryRevocation{}
	mi := &file_recovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRevocation) ProtoMessage() {}

func (x *RecoveryRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRevocation.ProtoReflect.Descriptor instead.
func (*RecoveryRevocation) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{5}
}

func (x *RecoveryRevocation) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RecoveryRevocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecoveryRevocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecoveryRevocation) GetSuccessor() string {
	if x != nil && x.Successor != nil {
		return *x.Successor
	}
	return ""
}

func (x *RecoveryRevocation) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *RecoveryRevocation) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// One level of the nested key chain. The outermost node is the active
// key; predecessor walks back to the signup key. signature is set only on
// predecessor links: the older key's signature over the newer key's armor.
type RecoveryKeyNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint     string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Armor           string                 `protobuf:"bytes,3,opt,name=armor,proto3" json:"armor,omitempty"`
	CreatedAt       uint32                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt       uint32                 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked         bool                   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,7,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Revocation      *RecoveryRevocation    `protobuf:"bytes,9,opt,name=revocation,proto3" json:"revocation,omitempty"`
	Predecessor     *RecoveryKeyNode       `protobuf:"bytes,10,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecoveryKeyNode) Reset() {
	*x = RecoveryKeyNode{}
	mi := &file_recovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryKeyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryKeyNode) ProtoMessage() {}

func (x *RecoveryKeyNode) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryKeyNode.ProtoReflect.Descriptor instead.
func (*RecoveryKeyNode) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{6}
}

func (x *RecoveryKeyNode) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RecoveryKeyNode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecoveryKeyNode) GetArmor() string {
	if x != nil {
		return x.Armor
	}
	return ""
}

func (x *RecoveryKeyNode) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RecoveryKeyNode) GetExpiresAt() uint32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RecoveryKeyNode) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RecoveryKeyNode) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *RecoveryKeyNode) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RecoveryKeyNode) GetRevocation() *RecoveryRevocation {
	if x != nil {
		return x.Revocation
	}
	return nil
}

func (x *RecoveryKeyNode) GetPredecessor() *RecoveryKeyNode {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

// POST /recovery/identity/claim.
type ClaimIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Profile       *RecoveryProfile       `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Key           *RecoveryKeyNode       `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimIdentityRequest) Reset() {
	*x = ClaimIdentityRequest{}
	mi := &file_recovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimIdentityRequest) ProtoMessage() {}

func (x *ClaimIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimIdentityRequest.ProtoReflect.Descriptor instead.
func (*ClaimIdentityRequest) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimIdentityRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *ClaimIdentityRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ClaimIdentityRequest) GetProfile() *RecoveryProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ClaimIdentityRequest) GetKey() *RecoveryKeyNode {
	if x != nil {
		return x.Key
	}
	return nil
}

// POST /recovery/identity.
type PeerIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *RecoveryProfile       `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Key           *RecoveryKeyNode       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerIdentityRequest) Reset() {
	*x = PeerIdentityRequest{}
	mi := &file_recovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerIdentityRequest) ProtoMessage() {}

func (x *PeerIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerIdentityRequest.ProtoReflect.Descriptor instead.
func (*PeerIdentityRequest) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{8}
}

func (x *PeerIdentityRequest) GetProfile() *RecoveryProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *PeerIdentityRequest) GetKey() *RecoveryKeyNode {
	if x != nil {
		return x.Key
	}
	return nil
}

// POST /recovery/reeds.
type RecoveryReedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReedId          string                 `protobuf:"bytes,1,opt,name=reed_id,json=reedID,proto3" json:"reed_id,omitempty"`
	AuthorId        string                 `protobuf:"bytes,2,opt,name=author_id,json=authorID,proto3" json:"author_id,omitempty"`
	UserSignature   *UserSignature         `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	ServerSignature *ServerSignature       `protobuf:"bytes,4,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecoveryReedRequest) Reset() {
	*x = RecoveryReedRequest{}
	mi := &file_recovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryReedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryReedRequest) ProtoMessage() {}

func (x *RecoveryReedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryReedRequest.ProtoReflect.Descriptor instead.
func (*RecoveryReedRequest) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{9}
}

func (x *RecoveryReedRequest) GetReedId() string {
	if x != nil {
		return x.ReedId
	}
	return ""
}

func (x *RecoveryReedRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *RecoveryReedRequest) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *RecoveryReedRequest) GetServerSignature() *ServerSignature {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// POST /recovery/following.
type RecoveryFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIDs,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryFollowingRequest) Reset() {
	*x = RecoveryFollowingRequest{}
	mi := &file_recovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryFollowingRequest) ProtoMessage() {}

func (x *RecoveryFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryFollowingRequest.ProtoReflect.Descriptor instead.
func (*RecoveryFollowingRequest) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{10}
}

func (x *RecoveryFollowingRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_recovery_proto protoreflect.FileDescriptor

const file_recovery_proto_rawDesc = "" +
	"\n" +
	"\x0erecovery.proto\x12\x06syrinx\x1a\fcommon.proto\x1a\x0eidentity.proto\"1\n" +
	"\x11ChallengeResponse\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\"\x8d\x01\n" +
	"\x1fAccountRecoveryBootstrapRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyID\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xb8\x01\n" +
	" AccountRecoveryBootstrapResponse\x12&\n" +
	"\aprofile\x18\x01 \x01(\v2\f.syrinx.UserR\aprofile\x12\x1c\n" +
	"\tfollowing\x18\x02 \x03(\tR\tfollowing\x12#\n" +
	"\vtip_reed_id\x18\x03 \x01(\tH\x00R\ttipReedID\x88\x01\x01\x12\x19\n" +
	"\breed_ids\x18\x04 \x03(\tR\areedIDsB\x0e\n" +
	"\f_tip_reed_id\"\x87\x03\n" +
	"\x0fRecoveryProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12!\n" +
	"\fmember_since\x18\x04 \x01(\rR\vmemberSince\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x124\n" +
	"\x16active_key_fingerprint\x18\x06 \x01(\tR\x14activeKeyFingerprint\x12<\n" +
	"\x0euser_signature\x18\a \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\b \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\x12\x1b\n" +
	"\thas_reeds\x18\t \x01(\bR\bhasReeds\x12*\n" +
	"\x06invite\x18\n" +
	" \x01(\v2\x12.syrinx.UserInviteR\x06invite\",\n" +
	"\x12UserStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x9a\x02\n" +
	"\x12RecoveryRevocation\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\tsuccessor\x18\x04 \x01(\tH\x00R\tsuccessor\x88\x01\x01\x12<\n" +
	"\x0euser_signature\x18\x05 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x06 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignatureB\f\n" +
	"\n" +
	"_successor\"\x93\x03\n" +
	"\x0fRecoveryKeyNode\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userID\x12\x14\n" +
	"\x05armor\x18\x03 \x01(\tR\x05armor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\rR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\rR\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked\x12B\n" +
	"\x10server_signature\x18\a \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12:\n" +
	"\n" +
	"revocation\x18\t \x01(\v2\x1a.syrinx.RecoveryRevocationR\n" +
	"revocation\x129\n" +
	"\vpredecessor\x18\n" +
	" \x01(\v2\x17.syrinx.RecoveryKeyNodeR\vpredecessor\"\xb0\x01\n" +
	"\x14ClaimIdentityRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x121\n" +
	"\aprofile\x18\x03 \x01(\v2\x17.syrinx.RecoveryProfileR\aprofile\x12)\n" +
	"\x03key\x18\x04 \x01(\v2\x17.syrinx.RecoveryKeyNodeR\x03key\"s\n" +
	"\x13PeerIdentityRequest\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.syrinx.RecoveryProfileR\aprofile\x12)\n" +
	"\x03key\x18\x02 \x01(\v2\x17.syrinx.RecoveryKeyNodeR\x03key\"\xcd\x01\n" +
	"\x13RecoveryReedRequest\x12\x17\n" +
	"\areed_id\x18\x01 \x01(\tR\x06reedID\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorID\x12<\n" +
	"\x0euser_signature\x18\x03 \x01(\v2\x15.syrinx.UserSignatureR\ruserSignature\x12B\n" +
	"\x10server_signature\x18\x04 \x01(\v2\x17.syrinx.ServerSignatureR\x0fserverSignature\"5\n" +
	"\x18RecoveryFollowingRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIDsB Z\x1egithub.com/alvaro/syrinx/protob\x06proto3"

var (
	file_recovery_proto_rawDescOnce sync.Once
	file_recovery_proto_rawDescData []byte
)

func file_recovery_proto_rawDescGZIP() []byte {
	file_recovery_proto_rawDescOnce.Do(func() {
		file_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recovery_proto_rawDesc), len(file_recovery_proto_rawDesc)))
	})
	return file_recovery_proto_rawDescData
}

var file_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recovery_proto_goTypes = []any{
	(*ChallengeResponse)(nil),                // 0: syrinx.ChallengeResponse
	(*AccountRecoveryBootstrapRequest)(nil),  // 1: syrinx.AccountRecoveryBootstrapRequest
	(*AccountRecoveryBootstrapResponse)(nil), // 2: syrinx.AccountRecoveryBootstrapResponse
	(*RecoveryProfile)(nil),                  // 3: syrinx.RecoveryProfile
	(*UserStatusResponse)(nil),               // 4: syrinx.UserStatusResponse
	(*RecoveryRevocation)(nil),               // 5: syrinx.RecoveryRevocation
	(*RecoveryKeyNode)(nil),                  // 6: syrinx.RecoveryKeyNode
	(*ClaimIdentityRequest)(nil),             // 7: syrinx.ClaimIdentityRequest
	(*PeerIdentityRequest)(nil),              // 8: syrinx.PeerIdentityRequest
	(*RecoveryReedRequest)(nil),              // 9: syrinx.RecoveryReedRequest
	(*RecoveryFollowingRequest)(nil),         // 10: syrinx.RecoveryFollowingRequest
	(*User)(nil),                             // 11: syrinx.User
	(*UserSignature)(nil),                    // 12: syrinx.UserSignature
	(*ServerSignature)(nil),                  // 13: syrinx.ServerSignature
	(*UserInvite)(nil),                       // 14: syrinx.UserInvite
}
var file_recovery_proto_depIdxs = []int32{
	11, // 0: syrinx.AccountRecoveryBootstrapResponse.profile:type_name -> syrinx.User
	12, // 1: syrinx.RecoveryProfile.user_signature:type_name -> syrinx.UserSignature
	13, // 2: syrinx.RecoveryProfile.server_signature:type_name -> syrinx.ServerSignature
	14, // 3: syrinx.RecoveryProfile.invite:type_name -> syrinx.UserInvite
	12, // 4: syrinx.RecoveryRevocation.user_signature:type_name -> syrinx.UserSignature
	13, // 5: syrinx.RecoveryRevocation.server_signature:type_name -> syrinx.ServerSignature
	13, // 6: syrinx.RecoveryKeyNode.server_signature:type_name -> syrinx.ServerSignature
	5,  // 7: syrinx.RecoveryKeyNode.revocation:type_name -> syrinx.RecoveryRevocation
	6,  // 8: syrinx.RecoveryKeyNode.predecessor:type_name -> syrinx.RecoveryKeyNode
	3,  // 9: syrinx.ClaimIdentityRequest.profile:type_name -> syrinx.RecoveryProfile
	6,  // 10: syrinx.ClaimIdentityRequest.key:type_name -> syrinx.RecoveryKeyNode
	3,  // 11: syrinx.PeerIdentityRequest.profile:type_name -> syrinx.RecoveryProfile
	6,  // 12: syrinx.PeerIdentityRequest.key:type_name -> syrinx.RecoveryKeyNode
	12, // 13: syrinx.RecoveryReedRequest.user_signature:type_name -> syrinx.UserSignature
	13, // 14: syrinx.RecoveryReedRequest.server_signature:type_name -> syrinx.ServerSignature
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_recovery_proto_init() }
func file_recovery_proto_init() {
	if File_recovery_proto != nil {
		return
	}
	file_common_proto_init()
	file_identity_proto_init()
	file_recovery_proto_msgTypes[2].OneofWrappers = []any{}
	file_recovery_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recovery_proto_rawDesc), len(file_recovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recovery_proto_goTypes,
		DependencyIndexes: file_recovery_proto_depIdxs,
		MessageInfos:      file_recovery_proto_msgTypes,
	}.Build()
	File_recovery_proto = out.File
	file_recovery_proto_goTypes = nil
	file_recovery_proto_depIdxs = nil
}
