// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file invites.proto (package syrinx, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ServerSignature, UserSignature } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file invites.proto.
 */
export const file_invites: GenFile = /*@__PURE__*/
  fileDesc("Cg1pbnZpdGVzLnByb3RvEgZzeXJpbngijgEKE0NyZWF0ZUludml0ZVJlcXVlc3QSCgoCaWQYASABKAkSEgoKdG9rZW5faGFzaBgCIAEoCRISCgpjcmVhdGVkX2F0GAMgASgDEhQKDGdyYW50ZWRfcm9sZRgEIAEoCRItCg51c2VyX3NpZ25hdHVyZRgFIAEoCzIVLnN5cmlueC5Vc2VyU2lnbmF0dXJlIrQBCgZJbnZpdGUSCgoCaWQYASABKAkSEgoKdG9rZW5faGFzaBgCIAEoCRISCgpjcmVhdGVkX2F0GAMgASgDEhQKDGdyYW50ZWRfcm9sZRgEIAEoCRItCg51c2VyX3NpZ25hdHVyZRgFIAEoCzIVLnN5cmlueC5Vc2VyU2lnbmF0dXJlEjEKEHNlcnZlcl9zaWduYXR1cmUYBiABKAsyFy5zeXJpbnguU2VydmVyU2lnbmF0dXJlIo4BCgxJbnZpdGVTdGF0dXMSCgoCaWQYASABKAkSEgoKY3JlYXRlZF9hdBgCIAEoAxIOCgZzdGF0dXMYAyABKAkSEgoKY2xhaW1lZF9hdBgEIAEoAxIXCgpjbGFpbWVkX2J5GAUgASgJSACIAQESEgoKcmV2b2tlZF9hdBgGIAEoA0INCgtfY2xhaW1lZF9ieSIkChNJbnZpdGVDaGVja1Jlc3BvbnNlEg0KBXZhbGlkGAEgASgIQiBaHmdpdGh1Yi5jb20vYWx2YXJvL3N5cmlueC9wcm90b2IGcHJvdG8z", [file_common]);

/**
 * POST /invites. The client mints id and secret; only the secret's
 * SHA-256 (token_hash) is sent.
 *
 * @generated from message syrinx.CreateInviteRequest
 */
export type CreateInviteRequest = Message<"syrinx.CreateInviteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string token_hash = 2;
   */
  tokenHash: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  /**
   * @generated from field: string granted_role = 4;
   */
  grantedRole: string;

  /**
   * @generated from field: syrinx.UserSignature user_signature = 5;
   */
  userSignature?: UserSignature | undefined;
};

/**
 * Describes the message syrinx.CreateInviteRequest.
 * Use `create(CreateInviteRequestSchema)` to create a new message.
 */
export const CreateInviteRequestSchema: GenMessage<CreateInviteRequest> = /*@__PURE__*/
  messageDesc(file_invites, 0);

/**
 * @generated from message syrinx.Invite
 */
export type Invite = Message<"syrinx.Invite"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string token_hash = 2;
   */
  tokenHash: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  /**
   * @generated from field: string granted_role = 4;
   */
  grantedRole: string;

  /**
   * @generated from field: syrinx.UserSignature user_signature = 5;
   */
  userSignature?: UserSignature | undefined;

  /**
   * @generated from field: syrinx.ServerSignature server_signature = 6;
   */
  serverSignature?: ServerSignature | undefined;
};

/**
 * Describes the message syrinx.Invite.
 * Use `create(InviteSchema)` to create a new message.
 */
export const InviteSchema: GenMessage<Invite> = /*@__PURE__*/
  messageDesc(file_invites, 1);

/**
 * GET /invites/{id}.
 *
 * @generated from message syrinx.InviteStatus
 */
export type InviteStatus = Message<"syrinx.InviteStatus"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 created_at = 2;
   */
  createdAt: bigint;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: int64 claimed_at = 4;
   */
  claimedAt: bigint;

  /**
   * @generated from field: optional string claimed_by = 5;
   */
  claimedBy?: string | undefined;

  /**
   * @generated from field: int64 revoked_at = 6;
   */
  revokedAt: bigint;
};

/**
 * Describes the message syrinx.InviteStatus.
 * Use `create(InviteStatusSchema)` to create a new message.
 */
export const InviteStatusSchema: GenMessage<InviteStatus> = /*@__PURE__*/
  messageDesc(file_invites, 2);

/**
 * GET /invites/check.
 *
 * @generated from message syrinx.InviteCheckResponse
 */
export type InviteCheckResponse = Message<"syrinx.InviteCheckResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;
};

/**
 * Describes the message syrinx.InviteCheckResponse.
 * Use `create(InviteCheckResponseSchema)` to create a new message.
 */
export const InviteCheckResponseSchema: GenMessage<InviteCheckResponse> = /*@__PURE__*/
  messageDesc(file_invites, 3);

